def even_fibonacci_numbers():
    """Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:
                                        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    find the sum of the even-valued terms."""
    fibonacci_numbers = [1, 2]
    while  fibonacci_numbers[-1] <= 4000000:
        if fibonacci_numbers[-1] + fibonacci_numbers[-2] > 4000000:
            break
        else:
            fibonacci_numbers.append(fibonacci_numbers[-2] + fibonacci_numbers[-1])

    even_numbers = [x for x in fibonacci_numbers if x % 2 == 0]
    return sum(even_numbers)

print(even_fibonacci_numbers())